[package]
name = "gav"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
mongodb = "3.2.3"
log = "0.4.26"

[lib]
name = "gavlib"
path = "src/lib.rs"

[[bin]]
name = "gavbin"
path = "src/bin.rs"

[[bin]]
name = "gavpwmanager"
path = "src/pwmanager/bin.rs"